"""Curated Australian English nickname mappings for PII name detection."""

NICKNAME_MAP = {
    "christopher": ["chris"],
    "elizabeth": ["beth", "liz", "lizzy", "eliza"],
    "katherine": ["kate", "kathy", "kat", "katie"],
    "catherine": ["cath", "cathy", "cat", "kate"],
    "william": ["will", "bill", "billy", "liam"],
    "benjamin": ["ben", "benji"],
    "nicholas": ["nick", "nico"],
    "alexander": ["alex", "xander"],
    "matthew": ["matt"],
    "daniel": ["dan", "danny"],
    "michael": ["mike", "mick", "mikey"],
    "joseph": ["joe", "joey"],
    "samuel": ["sam", "sammy"],
    "thomas": ["tom", "tommy"],
    "james": ["jim", "jimmy", "jamie"],
    "robert": ["rob", "bob", "bobby", "robbie"],
    "richard": ["rich", "rick", "dick"],
    "olivia": ["liv", "livy"],
    "victoria": ["vicky", "tori"],
    "jennifer": ["jen", "jenny"],
    "jessica": ["jess", "jessie"],
    "margaret": ["maggie", "meg", "peggy"],
    "stephanie": ["steph"],
    "natasha": ["tash", "nat"],
    "anthony": ["tony", "ant"],
    "andrew": ["andy", "drew"],
    "jonathan": ["jon", "jonny"],
    "timothy": ["tim", "timmy"],
    "rebecca": ["bec", "becca", "beck"],
    "alexandra": ["alex", "lexi"],
    "jacqueline": ["jackie"],
    "deborah": ["deb", "debbie"],
    "susan": ["sue", "suzy"],
    "patricia": ["pat", "patty", "trish"],
    "phillip": ["phil"],
    "stephen": ["steve"],
    "steven": ["steve"],
    "peter": ["pete"],
    "david": ["dave"],
    "edward": ["ed", "ted", "teddy"],
    "frederick": ["fred", "freddy"],
    "raymond": ["ray"],
    "lawrence": ["larry"],
    "nathan": ["nate"],
    "zachary": ["zach", "zac"],
    "cameron": ["cam"],
    "harrison": ["harry"],
    "dominic": ["dom"],
    "mitchell": ["mitch"],
    "isabella": ["bella", "izzy"],
    "gabrielle": ["gabby", "gab"],
    "madeline": ["maddy"],
    "charlotte": ["charlie", "lottie"],
    "madeleine": ["maddy"],
    "georgina": ["georgie"],
    "samantha": ["sam"],
    "abigail": ["abby"],
    "henrietta": ["henny"],
    "penelope": ["penny"],
    "theodore": ["theo"],
    "sebastian": ["seb"],
    "maximilian": ["max"],
    "beatrice": ["bea"],
    "josephine": ["josie"],
    "francesca": ["fran"],
    "angelina": ["angie"],
    "veronica": ["ronnie"],
    "cassandra": ["cass"],
    "genevieve": ["gen"],
    "annabelle": ["anna", "belle"],
    "callum": ["cal"],
    "connor": ["con"],
    "lachlan": ["lachy"],
    "declan": ["dec"],
    "arthur": ["art"],
    "rupert": ["rupe"],
    "hamish": ["hame"],
    "angus": ["gus"],
    "fergus": ["fergie"],
    "alistair": ["ali"],
    "bartholomew": ["bart"],
    "barnaby": ["barney"],
    "reginald": ["reg", "reggie"],
    "leonard": ["len", "lenny"],
    "kenneth": ["ken", "kenny"],
    "ronald": ["ron", "ronnie"],
    "donald": ["don", "donny"],
    "gerald": ["gerry"],
    "terence": ["terry"],
    "stuart": ["stu"],
    "nigel": ["nige"],
    "katrina": ["kat", "trina"],
    "melissa": ["mel"],
    "melanie": ["mel"],
    "danielle": ["dani"],
    "monique": ["mon"],
}

# Reverse map: nickname -> [formal names]
REVERSE_NICKNAME_MAP = {}
for _formal, _nicks in NICKNAME_MAP.items():
    for _nick in _nicks:
        REVERSE_NICKNAME_MAP.setdefault(_nick, []).append(_formal)
